# Generated by Django 4.2.18 on 2025-01-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_reservations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservations',
            name='time',
        ),
        migrations.AddField(
            model_name='reservations',
            name='note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
