# Generated by Django 4.2.18 on 2025-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_reservations_time_reservations_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='contact',
            field=models.CharField(default='', max_length=300, verbose_name='Phone number'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservations',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
